#Permanent aliases
alias ll="ls -l --color=auto"
alias la="ll -a"
alias s="sudo shutdown now"
alias uni="ssh wi21139@login.dhbw-stuttgart.de"
alias c="clear"
alias rwlan="sudo systemctl restart NetworkManager"
alias taskManager="htop"
alias xamppControl="sudo /opt/lampp/lampp"
alias xamppManage="cd /opt/lampp; sudo ./manager-linux-x64.run; cd"
alias xamppLogs="cat /opt/lampp/logs/php_error_log"
alias vim="nvim"
